# Generated by Django 4.0.5 on 2022-06-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_define_store_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='website',
            field=models.URLField(default='https://www.safeway.com/'),
            preserve_default=False,
        ),
    ]
