# Generated by Django 4.0.5 on 2022-06-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_add_website_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='directions',
            field=models.URLField(default='https://goo.gl/maps/MpQzbyER4Trxfq6o6'),
            preserve_default=False,
        ),
    ]
