# Generated by Django 4.0.5 on 2022-06-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_define_user_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='directions',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
