# Generated by Django 4.0.5 on 2022-06-19 03:16

import django.core.validators
from django.db import migrations, models
import quantityfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_default_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, validators=[
                                      django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=quantityfield.fields.QuantityField(
                base_units='ounce', default=1, unit_choices=['ounce']),
        ),
    ]
