# Generated by Django 4.0.5 on 2022-06-20 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_define_store_model'),
        ('products', '0006_define_brand_field_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductBrand',
            new_name='Brand',
        ),
    ]
