# Generated by Django 4.0.5 on 2022-06-21 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_productbrands_to_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
